[package]
name = "ap"
version = "0.0.2"
authors = ["Apollo <opensource@apollographql.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.26.0"
structopt = "0.2.10"
serde = "1.0" # why this?
serde_json = "1.0.48"
failure = "*"
json = "0.12"
graphql-parser = { path = "../graphql-parser" }

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
