[package]
name = "harmonizer"
version = "0.28.0"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
description = "Apollo Federation utility to compose a supergraph from subgraphs"
homepage = "https://www.apollographql.com/apollo-federation/"
documentation = "https://apollographql.com/docs/federation/"
repository = "https://github.com/apollographql/federation/"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

include = ["dist/**/*", "js/**/*", "src/**/*", "Cargo.toml"]

[dependencies]
anyhow = "1.0.39"
deno_core = "0.86.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.60"
thiserror = "1.0.23"

[dev-dependencies]
insta = "1.7.1"

[build-dependencies]
which = "4.2"
