[package]
name = "apollo-query-planner"
version = "0.0.1"
authors = ["Apollo <opensource@apollographql.com>"]
homepage = "https://github.com/apollographql/rust"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql-parser = { path = "../graphql-parser" }
lazy_static = "1.4.0"
linked-hash-map = "0.5.3"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"

[dev-dependencies]
cucumber = { package = "cucumber_rust", version = "^0.6.0" }

# Having this commented out is preventing the cucumber tests from running, but still compiles them. Uncomment to run them.
[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest
