[build]
  base    = "docs/"
  publish = "public/"
  command = "gatsby build --prefix-paths && mkdir -p docs/federation && mv public/* docs/federation && mv docs public/ && mv public/docs/federation/_redirects public"
  # Netlify tries to short-circuit when the build hasn't changed, but it's
  # presently wrong.  I would encourage removing this eventually, but for now,
  # we'll check to see if `/bin/false` returns true (it won't) as a gauge.
  ignore  = "/bin/false"
[build.environment]
  NODE_VERSION = "14"
  NPM_VERSION  = "7"
[dev]
  command = "npm run build"
[context.dev.environment]
  # SKIP_INDEXING = "false"
